# SPDX-FileCopyrightText: 2024 Nobody
# SPDX-License-Identifier: CC0-1.0

name: "[REUSE] Code Quality"

on: [push]

jobs:
  reuse:
    name: REUSE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: pipx run reuse lint
