# SPDX-FileCopyrightText: 2024-2025 Nobody
# SPDX-License-Identifier: CC0-1.0

name: "[Swift] Test"

on: [push]

jobs:
  swift-test:
    name: Swift Test
    runs-on: ubuntu-latest
    steps:
      - uses: yretenai/setup-swift@unsafe
        with:
          swift-version: 6.0.3
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Test
        run: swift test
